/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

namespace BinaryData
{

//================== SoundfontManifest.xml ==================
static const unsigned char temp_binary_data_0[] =
"<Soundfont>\n"
"    <Bank name=\"0\">\n"
"        <Preset name=\"Utility\" num=\"0\"/>\n"
"        <Preset name=\"sine long release\" num=\"1\"/>\n"
"        <Preset name=\"Square\" num=\"2\"/>\n"
"        <Preset name=\"Saw\" num=\"3\"/>\n"
"        <Preset name=\"Microrhythm\" num=\"4\"/>\n"
"        <Preset name=\"Electro\" num=\"6\"/>\n"
"        <Preset name=\"Electro Hi\" num=\"7\"/>\n"
"    </Bank>\n"
"    <Bank name=\"1\">\n"
"        <Preset name=\"Myriad\" num=\"0\"/>\n"
"        <Preset name=\"Puff\" num=\"1\"/>\n"
"        <Preset name=\"Moog Chimes\" num=\"2\"/>\n"
"        <Preset name=\"Quick Sweep\" num=\"3\"/>\n"
"        <Preset name=\"Tails\" num=\"4\"/>\n"
"        <Preset name=\"Prophet Release\" num=\"5\"/>\n"
"        <Preset name=\"Dream Pong\" num=\"6\"/>\n"
"        <Preset name=\"Ribbon\" num=\"7\"/>\n"
"        <Preset name=\"Silly String\" num=\"8\"/>\n"
"        <Preset name=\"Overtone\" num=\"9\"/>\n"
"        <Preset name=\"preset 355\" num=\"10\"/>\n"
"        <Preset name=\"preset 356\" num=\"11\"/>\n"
"        <Preset name=\"preset 357\" num=\"12\"/>\n"
"        <Preset name=\"preset 358\" num=\"13\"/>\n"
"        <Preset name=\"preset 359\" num=\"14\"/>\n"
"        <Preset name=\"preset 360\" num=\"15\"/>\n"
"        <Preset name=\"preset 361\" num=\"16\"/>\n"
"        <Preset name=\"preset 362\" num=\"17\"/>\n"
"        <Preset name=\"preset 363\" num=\"18\"/>\n"
"        <Preset name=\"preset 364\" num=\"19\"/>\n"
"        <Preset name=\"preset 365\" num=\"20\"/>\n"
"        <Preset name=\"preset 366\" num=\"21\"/>\n"
"        <Preset name=\"preset 367\" num=\"22\"/>\n"
"        <Preset name=\"preset 368\" num=\"23\"/>\n"
"        <Preset name=\"preset 369\" num=\"24\"/>\n"
"        <Preset name=\"preset 370\" num=\"25\"/>\n"
"        <Preset name=\"preset 371\" num=\"26\"/>\n"
"        <Preset name=\"preset 372\" num=\"27\"/>\n"
"        <Preset name=\"preset 373\" num=\"28\"/>\n"
"        <Preset name=\"preset 374\" num=\"29\"/>\n"
"        <Preset name=\"preset 375\" num=\"30\"/>\n"
"    </Bank>\n"
"    <Bank name=\"2\">\n"
"        <Preset name=\"Bows\" num=\"0\"/>\n"
"        <Preset name=\"Pizz\" num=\"1\"/>\n"
"        <Preset name=\"Deep Pizz\" num=\"2\"/>\n"
"        <Preset name=\"Staccatto\" num=\"3\"/>\n"
"        <Preset name=\"Violins\" num=\"4\"/>\n"
"        <Preset name=\"Trembling Viola\" num=\"5\"/>\n"
"        <Preset name=\"String Snip\" num=\"6\"/>\n"
"        <Preset name=\"Tremble Cello\" num=\"7\"/>\n"
"        <Preset name=\"Quartet\" num=\"8\"/>\n"
"        <Preset name=\"Fake String\" num=\"9\"/>\n"
"        <Preset name=\"Divisi\" num=\"10\"/>\n"
"        <Preset name=\"All Strings\" num=\"11\"/>\n"
"    </Bank>\n"
"    <Bank name=\"3\">\n"
"        <Preset name=\"Pianos\" num=\"0\"/>\n"
"        <Preset name=\"Piano Release\" num=\"1\"/>\n"
"        <Preset name=\"Short\" num=\"2\"/>\n"
"        <Preset name=\"Sliced\" num=\"3\"/>\n"
"        <Preset name=\"Staccato\" num=\"4\"/>\n"
"        <Preset name=\"Piano Normal\" num=\"5\"/>\n"
"        <Preset name=\"Harpsicord\" num=\"6\"/>\n"
"        <Preset name=\"Throat Piano\" num=\"7\"/>\n"
"        <Preset name=\"Uncalibrated\" num=\"8\"/>\n"
"        <Preset name=\"na-02\" num=\"9\"/>\n"
"        <Preset name=\"na-03\" num=\"10\"/>\n"
"        <Preset name=\"na-04\" num=\"11\"/>\n"
"    </Bank>\n"
"    <Bank name=\"4\">\n"
"        <Preset name=\"Brass\" num=\"0\"/>\n"
"        <Preset name=\"Flauta\" num=\"1\"/>\n"
"        <Preset name=\"Trombone\" num=\"2\"/>\n"
"        <Preset name=\"Moog Brass\" num=\"3\"/>\n"
"        <Preset name=\"Phila\" num=\"4\"/>\n"
"        <Preset name=\"Piper\" num=\"5\"/>\n"
"        <Preset name=\"Filter\" num=\"6\"/>\n"
"        <Preset name=\"Trumpet\" num=\"7\"/>\n"
"        <Preset name=\"Trumpets\" num=\"8\"/>\n"
"        <Preset name=\"OP1 Horns\" num=\"9\"/>\n"
"        <Preset name=\"Glown\" num=\"10\"/>\n"
"        <Preset name=\"Mellotron Horns\" num=\"11\"/>\n"
"    </Bank>\n"
"    <Bank name=\"5\">\n"
"        <Preset name=\"Reeds\" num=\"0\"/>\n"
"        <Preset name=\"Melodica A\" num=\"1\"/>\n"
"        <Preset name=\"Melodica B\" num=\"2\"/>\n"
"        <Preset name=\"Melodica Dark\" num=\"3\"/>\n"
"        <Preset name=\"Accordian\" num=\"4\"/>\n"
"        <Preset name=\"Accordian Squeeze\" num=\"5\"/>\n"
"        <Preset name=\"Short Reeds\" num=\"6\"/>\n"
"        <Preset name=\"Digital Reed\" num=\"7\"/>\n"
"        <Preset name=\"Bright LP\" num=\"8\"/>\n"
"        <Preset name=\"Thicken\" num=\"9\"/>\n"
"        <Preset name=\"Vibrato\" num=\"10\"/>\n"
"        <Preset name=\"na\" num=\"11\"/>\n"
"    </Bank>\n"
"    <Bank name=\"6\">\n"
"        <Preset name=\"Pipes\" num=\"0\"/>\n"
"        <Preset name=\"Prophet Organ\" num=\"1\"/>\n"
"        <Preset name=\"Demon\" num=\"2\"/>\n"
"        <Preset name=\"Wish\" num=\"3\"/>\n"
"        <Preset name=\"na-01\" num=\"4\"/>\n"
"        <Preset name=\"na-02\" num=\"5\"/>\n"
"        <Preset name=\"na-03\" num=\"6\"/>\n"
"        <Preset name=\"na-04\" num=\"7\"/>\n"
"        <Preset name=\"na-05\" num=\"8\"/>\n"
"        <Preset name=\"na-06\" num=\"9\"/>\n"
"        <Preset name=\"na-07\" num=\"10\"/>\n"
"        <Preset name=\"na-08\" num=\"11\"/>\n"
"    </Bank>\n"
"    <Bank name=\"7\">\n"
"        <Preset name=\"Mallet Bright\" num=\"0\"/>\n"
"        <Preset name=\"Springy\" num=\"1\"/>\n"
"        <Preset name=\"Gamma\" num=\"2\"/>\n"
"        <Preset name=\"Delicate\" num=\"3\"/>\n"
"        <Preset name=\"Honk\" num=\"4\"/>\n"
"        <Preset name=\"Vibra\" num=\"5\"/>\n"
"        <Preset name=\"Vibra Light\" num=\"6\"/>\n"
"        <Preset name=\"Glock Far\" num=\"7\"/>\n"
"        <Preset name=\"Glock Clear\" num=\"8\"/>\n"
"        <Preset name=\"Glock Short\" num=\"9\"/>\n"
"        <Preset name=\"Handbell Choir\" num=\"10\"/>\n"
"        <Preset name=\"Handbell Warp\" num=\"11\"/>\n"
"    </Bank>\n"
"    <Bank name=\"8\">\n"
"        <Preset name=\"Mallets\" num=\"0\"/>\n"
"        <Preset name=\"Bamboo Wash\" num=\"1\"/>\n"
"        <Preset name=\"Simple\" num=\"2\"/>\n"
"        <Preset name=\"Kalimba\" num=\"3\"/>\n"
"        <Preset name=\"Dirty\" num=\"4\"/>\n"
"        <Preset name=\"na-01\" num=\"5\"/>\n"
"        <Preset name=\"na-02\" num=\"6\"/>\n"
"        <Preset name=\"na-03\" num=\"7\"/>\n"
"        <Preset name=\"na-04\" num=\"8\"/>\n"
"        <Preset name=\"na-05\" num=\"9\"/>\n"
"        <Preset name=\"na-06\" num=\"10\"/>\n"
"        <Preset name=\"na-07\" num=\"11\"/>\n"
"        <Preset name=\"na-08\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"9\">\n"
"        <Preset name=\"Keys\" num=\"0\"/>\n"
"        <Preset name=\"Donkey\" num=\"1\"/>\n"
"        <Preset name=\"OP1\" num=\"2\"/>\n"
"        <Preset name=\"Deep\" num=\"3\"/>\n"
"        <Preset name=\"Glass\" num=\"4\"/>\n"
"        <Preset name=\"Quick\" num=\"5\"/>\n"
"        <Preset name=\"na-01\" num=\"6\"/>\n"
"        <Preset name=\"na-02\" num=\"7\"/>\n"
"        <Preset name=\"na-03\" num=\"8\"/>\n"
"        <Preset name=\"na-04\" num=\"9\"/>\n"
"        <Preset name=\"na-05\" num=\"10\"/>\n"
"        <Preset name=\"na-06\" num=\"11\"/>\n"
"        <Preset name=\"na-07\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"10\">\n"
"        <Preset name=\"Light Textures\" num=\"0\"/>\n"
"        <Preset name=\"Rink\" num=\"1\"/>\n"
"        <Preset name=\"Drawbar\" num=\"2\"/>\n"
"        <Preset name=\"Reversal\" num=\"3\"/>\n"
"        <Preset name=\"Acoustic Blaze\" num=\"4\"/>\n"
"        <Preset name=\"Moog\" num=\"5\"/>\n"
"        <Preset name=\"preset 249\" num=\"6\"/>\n"
"        <Preset name=\"Noise\" num=\"7\"/>\n"
"        <Preset name=\"na-01\" num=\"8\"/>\n"
"        <Preset name=\"na-02\" num=\"9\"/>\n"
"        <Preset name=\"na-03\" num=\"10\"/>\n"
"        <Preset name=\"na-04\" num=\"11\"/>\n"
"        <Preset name=\"na-05\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"11\">\n"
"        <Preset name=\"Moving Synthesizers\" num=\"0\"/>\n"
"        <Preset name=\"Geese\" num=\"1\"/>\n"
"        <Preset name=\"Glam\" num=\"2\"/>\n"
"        <Preset name=\"Rise\" num=\"3\"/>\n"
"        <Preset name=\"Gloom\" num=\"4\"/>\n"
"        <Preset name=\"Plick\" num=\"5\"/>\n"
"        <Preset name=\"Rip\" num=\"6\"/>\n"
"        <Preset name=\"Rope\" num=\"7\"/>\n"
"        <Preset name=\"Bug\" num=\"8\"/>\n"
"        <Preset name=\"Awe\" num=\"9\"/>\n"
"        <Preset name=\"Blue\" num=\"10\"/>\n"
"        <Preset name=\"preset 242\" num=\"11\"/>\n"
"        <Preset name=\"preset 243\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"12\">\n"
"        <Preset name=\"Bold Synthesizers\" num=\"0\"/>\n"
"        <Preset name=\"Saw\" num=\"1\"/>\n"
"        <Preset name=\"Klutz\" num=\"2\"/>\n"
"        <Preset name=\"Fifth\" num=\"3\"/>\n"
"        <Preset name=\"Lower\" num=\"4\"/>\n"
"        <Preset name=\"Charlie\" num=\"5\"/>\n"
"        <Preset name=\"Gaul\" num=\"6\"/>\n"
"        <Preset name=\"preset 226\" num=\"7\"/>\n"
"        <Preset name=\"Katz\" num=\"8\"/>\n"
"        <Preset name=\"na-01\" num=\"9\"/>\n"
"        <Preset name=\"na-02\" num=\"10\"/>\n"
"        <Preset name=\"na-03\" num=\"11\"/>\n"
"        <Preset name=\"na-04\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"13\">\n"
"        <Preset name=\"Vintage\" num=\"0\"/>\n"
"        <Preset name=\"Binky\" num=\"1\"/>\n"
"        <Preset name=\"Roll\" num=\"2\"/>\n"
"        <Preset name=\"Flut\" num=\"3\"/>\n"
"        <Preset name=\"One Ear\" num=\"4\"/>\n"
"        <Preset name=\"Arcade\" num=\"5\"/>\n"
"        <Preset name=\"Distance\" num=\"6\"/>\n"
"        <Preset name=\"Swall\" num=\"7\"/>\n"
"        <Preset name=\"Story\" num=\"8\"/>\n"
"        <Preset name=\"na-01\" num=\"9\"/>\n"
"        <Preset name=\"na-02\" num=\"10\"/>\n"
"        <Preset name=\"na-03\" num=\"11\"/>\n"
"        <Preset name=\"na-04\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"14\">\n"
"        <Preset name=\"Chips\" num=\"0\"/>\n"
"        <Preset name=\"na-01\" num=\"1\"/>\n"
"        <Preset name=\"na-02\" num=\"2\"/>\n"
"        <Preset name=\"na-03\" num=\"3\"/>\n"
"        <Preset name=\"na-04\" num=\"4\"/>\n"
"        <Preset name=\"na-05\" num=\"5\"/>\n"
"        <Preset name=\"na-06\" num=\"6\"/>\n"
"        <Preset name=\"na-07\" num=\"7\"/>\n"
"        <Preset name=\"na-08\" num=\"8\"/>\n"
"        <Preset name=\"na-09\" num=\"9\"/>\n"
"        <Preset name=\"na-10\" num=\"10\"/>\n"
"        <Preset name=\"na-11\" num=\"11\"/>\n"
"        <Preset name=\"preset 207\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"15\">\n"
"        <Preset name=\"Voices\" num=\"0\"/>\n"
"        <Preset name=\"Margot\" num=\"1\"/>\n"
"        <Preset name=\"Goo\" num=\"2\"/>\n"
"        <Preset name=\"Ghoul\" num=\"3\"/>\n"
"        <Preset name=\"Dead\" num=\"4\"/>\n"
"        <Preset name=\"Pops\" num=\"5\"/>\n"
"        <Preset name=\"Slide\" num=\"6\"/>\n"
"        <Preset name=\"Game Over\" num=\"7\"/>\n"
"        <Preset name=\"Glory\" num=\"8\"/>\n"
"        <Preset name=\"Rag\" num=\"9\"/>\n"
"        <Preset name=\"Ghost\" num=\"10\"/>\n"
"        <Preset name=\"na-01\" num=\"11\"/>\n"
"        <Preset name=\"na-02\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"16\">\n"
"        <Preset name=\"Short\" num=\"0\"/>\n"
"        <Preset name=\"Castle\" num=\"1\"/>\n"
"        <Preset name=\"Softer\" num=\"2\"/>\n"
"        <Preset name=\"Softest\" num=\"3\"/>\n"
"        <Preset name=\"Simple\" num=\"4\"/>\n"
"    </Bank>\n"
"    <Bank name=\"17\">\n"
"        <Preset name=\"Pluck\" num=\"0\"/>\n"
"        <Preset name=\"Harp\" num=\"1\"/>\n"
"        <Preset name=\"String\" num=\"2\"/>\n"
"        <Preset name=\"Bottle\" num=\"3\"/>\n"
"        <Preset name=\"preset 171\" num=\"4\"/>\n"
"        <Preset name=\"na-01\" num=\"5\"/>\n"
"        <Preset name=\"na-02\" num=\"6\"/>\n"
"        <Preset name=\"na-03\" num=\"7\"/>\n"
"        <Preset name=\"na-04\" num=\"8\"/>\n"
"        <Preset name=\"na-05\" num=\"9\"/>\n"
"        <Preset name=\"na-06\" num=\"10\"/>\n"
"        <Preset name=\"na-07\" num=\"11\"/>\n"
"        <Preset name=\"harpen\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"18\">\n"
"        <Preset name=\"Hard\" num=\"0\"/>\n"
"        <Preset name=\"na-01\" num=\"1\"/>\n"
"        <Preset name=\"na-02\" num=\"2\"/>\n"
"        <Preset name=\"na-03\" num=\"3\"/>\n"
"        <Preset name=\"na-04\" num=\"4\"/>\n"
"        <Preset name=\"na-05\" num=\"5\"/>\n"
"        <Preset name=\"na-06\" num=\"6\"/>\n"
"        <Preset name=\"na-07\" num=\"7\"/>\n"
"        <Preset name=\"na-08\" num=\"8\"/>\n"
"        <Preset name=\"na-09\" num=\"9\"/>\n"
"        <Preset name=\"na-10\" num=\"10\"/>\n"
"        <Preset name=\"na-11\" num=\"11\"/>\n"
"        <Preset name=\"na-12\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"19\">\n"
"        <Preset name=\"Guitar\" num=\"0\"/>\n"
"        <Preset name=\"Cable\" num=\"1\"/>\n"
"        <Preset name=\"Telecaster\" num=\"2\"/>\n"
"        <Preset name=\"Telecaster Swarm\" num=\"3\"/>\n"
"        <Preset name=\"Broken Acoustic\" num=\"4\"/>\n"
"        <Preset name=\"Steel\" num=\"5\"/>\n"
"        <Preset name=\"Hohner\" num=\"6\"/>\n"
"        <Preset name=\"Acoustic\" num=\"7\"/>\n"
"        <Preset name=\"Echo\" num=\"8\"/>\n"
"        <Preset name=\"Slip\" num=\"9\"/>\n"
"        <Preset name=\"na-01\" num=\"10\"/>\n"
"        <Preset name=\"na-02\" num=\"11\"/>\n"
"        <Preset name=\"na-03\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"20\">\n"
"        <Preset name=\"Organic Perc\" num=\"0\"/>\n"
"        <Preset name=\"na-01\" num=\"1\"/>\n"
"        <Preset name=\"na-02\" num=\"2\"/>\n"
"        <Preset name=\"na-03\" num=\"3\"/>\n"
"        <Preset name=\"na-04\" num=\"4\"/>\n"
"        <Preset name=\"na-05\" num=\"5\"/>\n"
"        <Preset name=\"na-06\" num=\"6\"/>\n"
"        <Preset name=\"na-07\" num=\"7\"/>\n"
"        <Preset name=\"na-08\" num=\"8\"/>\n"
"        <Preset name=\"na-09\" num=\"9\"/>\n"
"        <Preset name=\"na-10\" num=\"10\"/>\n"
"        <Preset name=\"na-11\" num=\"11\"/>\n"
"        <Preset name=\"na-12\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"21\">\n"
"        <Preset name=\"Digital Percussion\" num=\"0\"/>\n"
"        <Preset name=\"preset 120\" num=\"1\"/>\n"
"        <Preset name=\"na-01\" num=\"2\"/>\n"
"        <Preset name=\"na-02\" num=\"3\"/>\n"
"        <Preset name=\"na-03\" num=\"4\"/>\n"
"        <Preset name=\"na-04\" num=\"5\"/>\n"
"        <Preset name=\"na-05\" num=\"6\"/>\n"
"        <Preset name=\"na-06\" num=\"7\"/>\n"
"        <Preset name=\"na-07\" num=\"8\"/>\n"
"        <Preset name=\"na-08\" num=\"9\"/>\n"
"        <Preset name=\"na-09\" num=\"10\"/>\n"
"        <Preset name=\"na-10\" num=\"11\"/>\n"
"        <Preset name=\"na-11\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"22\">\n"
"        <Preset name=\"Tactillian\" num=\"0\"/>\n"
"        <Preset name=\"Tactillian-01\" num=\"1\"/>\n"
"        <Preset name=\"Tactillian-02\" num=\"2\"/>\n"
"        <Preset name=\"Tactillian-03\" num=\"3\"/>\n"
"        <Preset name=\"Tactillian-04\" num=\"4\"/>\n"
"        <Preset name=\"Tactillian-05\" num=\"5\"/>\n"
"        <Preset name=\"Tactillian-06\" num=\"6\"/>\n"
"        <Preset name=\"Tactillian-07\" num=\"7\"/>\n"
"        <Preset name=\"Tactillian-08\" num=\"8\"/>\n"
"        <Preset name=\"Tactillian-09\" num=\"9\"/>\n"
"        <Preset name=\"Tactillian-10\" num=\"10\"/>\n"
"        <Preset name=\"Tactillian-11\" num=\"11\"/>\n"
"        <Preset name=\"Tactillian-12\" num=\"12\"/>\n"
"        <Preset name=\"Tactillian-13\" num=\"13\"/>\n"
"        <Preset name=\"Tactillian-14\" num=\"14\"/>\n"
"        <Preset name=\"Tactillian-15\" num=\"15\"/>\n"
"        <Preset name=\"Tactillian-16\" num=\"16\"/>\n"
"        <Preset name=\"Tactillian-17\" num=\"17\"/>\n"
"        <Preset name=\"Tactillian-18\" num=\"18\"/>\n"
"        <Preset name=\"Tactillian-19\" num=\"19\"/>\n"
"        <Preset name=\"Tactillian-20\" num=\"20\"/>\n"
"    </Bank>\n"
"    <Bank name=\"23\">\n"
"        <Preset name=\"Bananas\" num=\"0\"/>\n"
"        <Preset name=\"Cheer\" num=\"1\"/>\n"
"        <Preset name=\"Slope\" num=\"2\"/>\n"
"        <Preset name=\"Horror\" num=\"3\"/>\n"
"        <Preset name=\"Phantom\" num=\"4\"/>\n"
"        <Preset name=\"Delta\" num=\"5\"/>\n"
"        <Preset name=\"na-01\" num=\"6\"/>\n"
"        <Preset name=\"na-02\" num=\"7\"/>\n"
"        <Preset name=\"na-03\" num=\"8\"/>\n"
"        <Preset name=\"na-04\" num=\"9\"/>\n"
"        <Preset name=\"na-05\" num=\"10\"/>\n"
"        <Preset name=\"na-06\" num=\"11\"/>\n"
"    </Bank>\n"
"    <Bank name=\"24\">\n"
"        <Preset name=\"Hydra\" num=\"0\"/>\n"
"        <Preset name=\"Optigon\" num=\"1\"/>\n"
"        <Preset name=\"Hydra-01\" num=\"2\"/>\n"
"        <Preset name=\"Hydra-02\" num=\"3\"/>\n"
"        <Preset name=\"Hydra-03\" num=\"4\"/>\n"
"        <Preset name=\"Hydra-04\" num=\"5\"/>\n"
"        <Preset name=\"Hydra-05\" num=\"6\"/>\n"
"        <Preset name=\"Hydra-06\" num=\"7\"/>\n"
"        <Preset name=\"Hydra-07\" num=\"8\"/>\n"
"        <Preset name=\"Hydra-08\" num=\"9\"/>\n"
"        <Preset name=\"Hydra-09\" num=\"10\"/>\n"
"        <Preset name=\"Hydra-10\" num=\"11\"/>\n"
"        <Preset name=\"Hydra-11\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"25\">\n"
"        <Preset name=\"Manipulated\" num=\"0\"/>\n"
"        <Preset name=\"Lightbox\" num=\"1\"/>\n"
"        <Preset name=\"KB\" num=\"2\"/>\n"
"        <Preset name=\"Cloud\" num=\"3\"/>\n"
"        <Preset name=\"Digital Divide\" num=\"4\"/>\n"
"        <Preset name=\"Addition\" num=\"5\"/>\n"
"        <Preset name=\"Rumble\" num=\"6\"/>\n"
"        <Preset name=\"Angel\" num=\"7\"/>\n"
"        <Preset name=\"Swamp\" num=\"8\"/>\n"
"        <Preset name=\"Cyborg\" num=\"9\"/>\n"
"        <Preset name=\"Sharp\" num=\"10\"/>\n"
"        <Preset name=\"preset 75\" num=\"11\"/>\n"
"        <Preset name=\"preset 76\" num=\"12\"/>\n"
"    </Bank>\n"
"    <Bank name=\"26\">\n"
"        <Preset name=\"Scary\" num=\"0\"/>\n"
"    </Bank>\n"
"    <Bank name=\"27\">\n"
"        <Preset name=\"NES\" num=\"0\"/>\n"
"        <Preset name=\"NES-02\" num=\"1\"/>\n"
"        <Preset name=\"NES-03\" num=\"2\"/>\n"
"        <Preset name=\"NES-04\" num=\"3\"/>\n"
"        <Preset name=\"NES-05\" num=\"4\"/>\n"
"        <Preset name=\"NES-06\" num=\"5\"/>\n"
"        <Preset name=\"NES-07\" num=\"6\"/>\n"
"        <Preset name=\"NES-08\" num=\"7\"/>\n"
"        <Preset name=\"NES-09\" num=\"8\"/>\n"
"        <Preset name=\"NES-10\" num=\"9\"/>\n"
"        <Preset name=\"NES-11\" num=\"10\"/>\n"
"        <Preset name=\"NES-12\" num=\"11\"/>\n"
"        <Preset name=\"NES-13\" num=\"12\"/>\n"
"        <Preset name=\"NES-14\" num=\"13\"/>\n"
"        <Preset name=\"NES-15\" num=\"14\"/>\n"
"        <Preset name=\"NES-16\" num=\"15\"/>\n"
"        <Preset name=\"NES-17\" num=\"16\"/>\n"
"        <Preset name=\"NES-18\" num=\"17\"/>\n"
"        <Preset name=\"NES-19\" num=\"18\"/>\n"
"        <Preset name=\"NES-20\" num=\"19\"/>\n"
"        <Preset name=\"NES-21\" num=\"20\"/>\n"
"        <Preset name=\"NES-22\" num=\"21\"/>\n"
"        <Preset name=\"NES-23\" num=\"22\"/>\n"
"        <Preset name=\"NES-24\" num=\"23\"/>\n"
"        <Preset name=\"NES-25\" num=\"24\"/>\n"
"        <Preset name=\"NES-26\" num=\"25\"/>\n"
"        <Preset name=\"NES-27\" num=\"26\"/>\n"
"        <Preset name=\"NES-28\" num=\"27\"/>\n"
"        <Preset name=\"NES-29\" num=\"28\"/>\n"
"        <Preset name=\"NES-30\" num=\"29\"/>\n"
"        <Preset name=\"NES-31\" num=\"30\"/>\n"
"        <Preset name=\"NES-32\" num=\"31\"/>\n"
"        <Preset name=\"NES-33\" num=\"32\"/>\n"
"        <Preset name=\"NES-34\" num=\"33\"/>\n"
"        <Preset name=\"NES-35\" num=\"34\"/>\n"
"        <Preset name=\"NES-36\" num=\"35\"/>\n"
"        <Preset name=\"NES-37\" num=\"36\"/>\n"
"    </Bank>\n"
"    <Bank name=\"99\">\n"
"        <Preset name=\"Algo Range\" num=\"0\"/>\n"
"        <Preset name=\"Velocity Test\" num=\"1\"/>\n"
"    </Bank>\n"
"</Soundfont>\n";

const char* SoundfontManifest_xml = (const char*) temp_binary_data_0;


const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)
{
    unsigned int hash = 0;

    if (resourceNameUTF8 != nullptr)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0x03a9fae5:  numBytes = 16840; return SoundfontManifest_xml;
        default: break;
    }

    numBytes = 0;
    return nullptr;
}

const char* namedResourceList[] =
{
    "SoundfontManifest_xml"
};

const char* originalFilenames[] =
{
    "SoundfontManifest.xml"
};

const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8)
{
    for (unsigned int i = 0; i < (sizeof (namedResourceList) / sizeof (namedResourceList[0])); ++i)
    {
        if (namedResourceList[i] == resourceNameUTF8)
            return originalFilenames[i];
    }

    return nullptr;
}

}
